
        
            def notify_call_escalated(self, call):
        pass
    
    
def test_index(client, auth):
    response = client.get('/')
    assert b'Log In' in response.data
    assert b'Register' in response.data
    
        def loads(self, value):
        '''Load data from a JSON string and deserialized any tagged objects.'''
        return loads(value, object_hook=self.untag)

    
            def __init__(self, name, doc=None):
            self.name = name
            self.__doc__ = doc
        def _fail(self, *args, **kwargs):
            raise RuntimeError('signalling support is unavailable '
                               'because the blinker library is '
                               'not installed.')
        send = lambda *a, **kw: None
        connect = disconnect = has_receivers_for = receivers_for = \
            temporarily_connected_to = connected_to = _fail
        del _fail
    
        #: A list of methods this view can handle.
    methods = None
    
        return inner
    
        def appid_exist(self, appids):
        for appid in appids.split('|'):
            if appid == '':
                continue
            if appid in self.config.GAE_APPIDS:
                return True
        return False
    
            if response.status == 503:
            # out of quota
            if 'gws' not in server_type and 'Google Frontend' not in server_type and 'GFE' not in server_type:
                xlog.warn('503 but server type:%s', server_type)
                return False
            else:
                return True
    
    This module contains all support classes, which are needed to use recognizers
generated by ANTLR3.
    
    
    def error(self, nvae):
        '''A hook for debugging interface'''
        pass
    
    
    def __str__(self):
        if self.inserted is not None and self.token is not None:
            return 'MissingTokenException(inserted %r at %r)' % (
                self.inserted, self.token.text)
    
        This implementation does not copy the text from the input stream upon
    creation, but keeps start/stop pointers into the stream to avoid
    unnecessary copy operations.